In [1]:
#Librerías
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
import mysql.connector
from math import floor
from scipy.stats import norm
from collections import defaultdict
from sklearn.impute import KNNImputer

from io import BytesIO
import xlsxwriter
import re
from scipy.signal import savgol_filter  

from tqdm import tqdm

from sklearn.preprocessing import MinMaxScaler

from scipy import stats

In [5]:
archivo1 = pd.read_csv('UMPAS_FABIO//categoria_establecimientos_19122024 1.csv',sep=';')

In [7]:
archivo2 = pd.read_excel('UMPAS_FABIO//categorizacion_establecimientos_31_12_2024_00.xlsx')

In [8]:
archivo1.head(5)

      numero_ruc  id_establecimiento                      categoria
0   151822624001     151822624001002  Restaurantes de comida rápida
1  1792915031001    1792915031001001                     Automotriz
2   991331859001     991331859001101                    Gasolineras
3   910439769001     910439769001011              Moda y Accesorios
4   924728660001     924728660001003                   Restaurantes

In [9]:
archivo2.head(5)

     numero_ruc  id_establecimiento         categoria
0  790017552001     790017552001001  Viajes y Turismo
1  790017552001     790017552001002  Viajes y Turismo
2  991330909001     991330909001001     Bienes Raíces
3  991331433001     991331433001006        Automotriz
4  991331859001     991331859001001       Gasolineras

In [10]:
archivo1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15107 entries, 0 to 15106
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   numero_ruc          15107 non-null  int64
 1   id_establecimiento  15107 non-null  int64
 2   categoria           15107 non-null  object
dtypes: int64(2), object(1)
memory usage: 354.2+ KB

In [11]:
archivo2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12766 entries, 0 to 12765
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   numero_ruc          12766 non-null  int64
 1   id_establecimiento  12766 non-null  int64
 2   categoria           12766 non-null  object
dtypes: int64(2), object(1)
memory usage: 299.3+ KB

In [15]:
12766+15107

27873

In [12]:
base = pd.concat([archivo1, archivo2], axis=0)

In [14]:
base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27873 entries, 0 to 12765
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   numero_ruc          27873 non-null  int64
 1   id_establecimiento  27873 non-null  int64
 2   categoria           27873 non-null  object
dtypes: int64(2), object(1)
memory usage: 871.0+ KB

In [28]:
base.head(17)

       numero_ruc id_establecimiento                      categoria
0    151822624001    151822624001002  Restaurantes de comida rápida
1   1792915031001   1792915031001001                     Automotriz
2    991331859001    991331859001101                    Gasolineras
3    910439769001    910439769001011              Moda y Accesorios
4    924728660001    924728660001003                   Restaurantes
5   1707898159001   1707898159001010                   Restaurantes
6   1793198465001   1793198465001003                   Restaurantes
7   1793198465001   1793198465001002                   Restaurantes
8   1793198465001   1793198465001001                   Restaurantes
9   1712490091001   1712490091001001                  Supermercados
10   993227943001    993227943001001       Electrónica y Tecnología
11   991331859001    991331859001034                    Gasolineras
12   991331859001    991331859001023                    Gasolineras
13  1793206335001   1793206335001001  Restaurantes de comida rápida
14  1757274624001   1757274624001002       Electrónica y Tecnología
15   100733096001    100733096001001        Servicios Profesionales
16  1720901121001   1720901121001001             Bebés y Maternidad

In [18]:
len(base["id_establecimiento"].unique())

27873

In [19]:
cat = (
    base.groupby(['categoria'], as_index=False)
      .agg(establecimientos=('id_establecimiento', 'count') )
)

In [20]:
cat

                                    categoria  establecimientos
0                                  Automotriz              1143
1                          Bebés y Maternidad                57
2                  Belleza y Cuidado Personal               554
3                               Bienes Raíces               251
4                          Correo y Logística               336
5                          Deportes y Outdoor               377
6                    Educación y Capacitación               573
7                    Electrónica y Tecnología               947
8                                 Gasolineras              1141
9                          Hogar y Decoración              1353
10                                  Industria              1395
11                       Juegos y Videojuegos                37
12                          Juguetes y Juegos               129
13           Libros, Música y Entretenimiento               559
14                       Licorerías y bodegas               119
15                                   Mascotas               348
16                          Moda y Accesorios              1861
17                               Restaurantes              4386
18              Restaurantes de comida rápida              1683
19                          Salud y Bienestar              4521
20            Servicios Financieros y Seguros               438
21                    Servicios Profesionales              1293
22                    Servicios profesionales                 1
23                         Servicios públicos               544
24                              Supermercados              2706
25  Telecomunicaciones y televisión por cable               189
26                           Viajes y Turismo               932

In [26]:
base['numero_ruc'] = base['numero_ruc'].astype('object')
base['id_establecimiento'] = base['id_establecimiento'].astype('object')

In [29]:
base.to_csv("categorizacion_establecimientos_13_01_2025.csv",index=False)